### ISSUE TITLE
PG::UndefinedTable: ERROR:  relation "users" does not exist

### ISSUE THREAD

**Issue by moh-alsheikh** [collectiveidea/audited#164]
I receive the following errors when i try to run migration this happen only when I specify audited columns in User Model

audited only: [:email]

```
PG::UndefinedTable: ERROR:  relation "users" does not exist
LINE 5:              WHERE a.attrelid = '"users"'::regclass
                                        ^
:             SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
              FROM pg_attribute a LEFT JOIN pg_attrdef d
                ON a.attrelid = d.adrelid AND a.attnum = d.adnum
             WHERE a.attrelid = '"users"'::regclass
               AND a.attnum > 0 AND NOT a.attisdropped
             ORDER BY a.attnum
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `exec'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `exec_no_cache'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:662:in `block in exec_query'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:280:in `block in log'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:275:in `log'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `exec_query'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1278:in `column_definitions'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:857:in `columns'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/connection_adapters/schema_cache.rb:12:in `block in initialize'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `yield'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `default'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:228:in `columns'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/activerecord-3.2.12/lib/active_record/model_schema.rb:248:in `column_names'
/Users/mohammed/.rvm/gems/ruby-1.9.3-p286/gems/audited-3.0.0/lib/audited/auditor.rb:55:in `audited'
/Users/mohammed/Desktop/RubyONRails/railsproj/aqary/app/models/user.rb:46:in `<class:User>'
/Users/mohammed/Desktop/RubyONRails/railsproj/aqary/app/models/user.rb:3:in `<top (required)>'
```

Thanks for help

**Comment by piya23300** [comment]
+1 
PR #78 work!

**Comment by curtis** [comment]
I just ran across this in CI, when it tried to `bundle exec rake db:schema:load`. The workaround I used was just to ensure the table exists first.

```ruby
if User.table_exists?
  audited only: [:email]
end
```

**Comment by tbrisker** [comment]
This has been solved by https://github.com/collectiveidea/audited/pull/285 AFAICT, closing for now, please reopen if issue still exits.
