### ISSUE TITLE
undefined method `request_uuid' for #<Audited::Adapters::ActiveRecord::Audit:0x007faab980ba90>

### ISSUE THREAD

**Issue by heaven** [collectiveidea/audited#193]
```
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activemodel-4.1.6/lib/active_model/attribute_methods.rb:435:in `method_missing'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/attribute_methods.rb:211:in `method_missing'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/audited-4.0.0/lib/audited/audit.rb:101:in `set_request_uuid'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:424:in `block in make_lambda'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:160:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:160:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:306:in `_create_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/timestamp.rb:57:in `_create_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/persistence.rb:483:in `create_or_update'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `block in create_or_update'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `create_or_update'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/persistence.rb:103:in `save'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/validations.rb:51:in `save'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/attribute_methods/dirty.rb:21:in `save'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:268:in `block (2 levels) in save'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:208:in `transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:268:in `block in save'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:283:in `rollback_active_record_state!'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:267:in `save'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/associations/has_many_association.rb:40:in `insert_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:44:in `block (2 levels) in create_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/associations/collection_association.rb:389:in `add_to_target'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:42:in `block in create_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/associations/collection_association.rb:168:in `block in transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:199:in `transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:208:in `transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/associations/collection_association.rb:167:in `transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:41:in `create_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:26:in `create'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/protected_attributes-1.0.8/lib/active_record/mass_assignment_security/associations.rb:60:in `create'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/audited-4.0.0/lib/audited/auditor.rb:206:in `block in write_audit'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:321:in `block in conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:239:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:239:in `block in conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/audited-4.0.0/lib/audited/auditor.rb:206:in `write_audit'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/audited-4.0.0/lib/audited/auditor.rb:187:in `audit_create'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:424:in `block in make_lambda'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:221:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:221:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:306:in `_create_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/timestamp.rb:57:in `_create_record'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/persistence.rb:483:in `create_or_update'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `block in create_or_update'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:215:in `block in halting_and_conditional'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/callbacks.rb:302:in `create_or_update'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/persistence.rb:125:in `save!'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/validations.rb:57:in `save!'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/attribute_methods/dirty.rb:29:in `save!'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:273:in `block in save!'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:329:in `block in with_transaction_returning_status'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:208:in `transaction'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:326:in `with_transaction_returning_status'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activerecord-4.1.6/lib/active_record/transactions.rb:273:in `save!'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/configuration.rb:14:in `block in initialize'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/evaluation.rb:15:in `[]'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/evaluation.rb:15:in `create'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/strategy/create.rb:12:in `block in result'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/strategy/create.rb:9:in `tap'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/strategy/create.rb:9:in `result'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/factory.rb:42:in `run'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/factory_runner.rb:22:in `run'
# ~/.rvm/gems/ruby-2.1.2@carmen/gems/factory_girl-4.4.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
# ./spec/controllers/admin/email_addresses_controller_spec.rb:8:in `block (2 levels) in <top (required)>' 
```

**Comment by aripollak** [comment]
The incoming request ID isn't guaranteed to be 36 characters if it's being generated by something outside of Rails, like a proxying webserver. Postgres character varying fields aren't any more space-efficient or performant with a smaller maximum size. Are there other databases that are?

**Comment by kennethkalmer** [comment]
Wow, thanks @aripollak for pointing out that external systems could set the value, I never knew!
