### ISSUE TITLE
[bug] Can't verify CSRF token authenticity

### ISSUE THREAD

**Issue by lucianosousa** [collectiveidea/audited#343]
I'm trying to upgrade an rails4 app and received this error when tried to login on activeadmin.
Debugging the app, looks like the problem is in `lib/audited/sweeper.rb:14:in 'around'`

```
actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:195:in `handle_unverified_request'
actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
devise (4.2.1) lib/devise/controllers/helpers.rb:253:in `handle_unverified_request'
actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'
activesupport (5.0.2) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.2) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
actionpack (5.0.2) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
activesupport (5.0.2) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
audited (4.4.1) lib/audited/sweeper.rb:14:in `around'
activesupport (5.0.2) lib/active_support/callbacks.rb:405:in `public_send'
activesupport (5.0.2) lib/active_support/callbacks.rb:405:in `block in make_lambda'
activesupport (5.0.2) lib/active_support/callbacks.rb:285:in `block in halting'
activesupport (5.0.2) lib/active_support/callbacks.rb:447:in `block in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
audited (4.4.1) lib/audited/sweeper.rb:14:in `around'
```

I build an example here: https://github.com/lucianosousa/rails5_test
If you remove the audited gem, everything works fine.
Any tips?

**Comment by lucianosousa** [comment]
just an example:
commented these lines and works fine

```
    def around(controller)
#      self.controller = controller
#      STORED_DATA.each { |k,m| store[k] = send(m) }
      yield
    ensure
      self.controller = nil
      STORED_DATA.keys.each { |k| store.delete(k) }
    end
```

**Comment by lucianosousa** [comment]
also, removed current_user on

```
    STORED_DATA = {
      current_remote_address: :remote_ip,
      current_request_uuid: :request_uuid,
      current_user: :current_user
    }
```

and works fine

**Comment by lucianosousa** [comment]
rollback to v4.3 also works fine

**Comment by andrkrn** [comment]
I encounter same issue.

```
  actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:223:in `handle_unverified_request'
  devise (4.2.1) lib/devise/controllers/helpers.rb:253:in `handle_unverified_request'
  actionpack (5.0.2) lib/action_controller/metal/request_forgery_protection.rb:218:in `verify_authenticity_token'
  activesupport (5.0.2) lib/active_support/callbacks.rb:382:in `block in make_lambda'
  activesupport (5.0.2) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
  actionpack (5.0.2) lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
  activesupport (5.0.2) lib/active_support/callbacks.rb:170:in `block in halting'
  activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `block in call'
  activesupport (5.0.2) lib/active_support/callbacks.rb:454:in `call'
  activesupport (5.0.2) lib/active_support/callbacks.rb:448:in `block (2 levels) in around'
  activesupport (5.0.2) lib/active_support/callbacks.rb:286:in `block (2 levels) in halting'
  audited (4.4.1) lib/audited/sweeper.rb:14:in `around'
```

rollback to v4.3, thanks mate for the info

**Comment by domcleal** [comment]
Thanks for the report. What I think is happening is that calling `current_user` from the audited around filter is reordering some of the activeadmin or devise authentication/session change process during login to activeadmin.

I'll try and address this with a patch for #336 to delay the `current_user` call.

**Comment by lucianosousa** [comment]
thanks @domcleal
