### ISSUE TITLE
ActiveRecord lazy initialization

### ISSUE THREAD

**Issue by akostadinov** [collectiveidea/audited#599]
Hi, audited causes pre-mature ActiveRecord initialization before all initializers have run, thus some configuration options might be missing when ActiveRecord becomes loaded.

I have this check to see what has caused ActiveRecord loading:
```ruby
ActiveSupport.on_load(:active_record) { puts "ActiveRecord init:\n", *caller.map{|l| "  #{l}" }}
```

And I see this in console:
```
$ rails db:seed
ActiveRecord init:
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:49:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/base.rb:326:in `<module:ActiveRecord>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/base.rb:25:in `<top (required)>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/audited-5.0.1/lib/audited/audit.rb:42:in `require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/audited-5.0.1/lib/audited/audit.rb:42:in `<module:Audited>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/audited-5.0.1/lib/audited/audit.rb:5:in `<top (required)>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/audited-5.0.1/lib/audited.rb:42:in `require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/audited-5.0.1/lib/audited.rb:42:in `<top (required)>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/runtime.rb:60:in `require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/runtime.rb:55:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/runtime.rb:55:in `block in require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/runtime.rb:44:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler/runtime.rb:44:in `require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bundler-2.2.25/lib/bundler.rb:174:in `require'
  /home/user/ws/repos/porta/config/application.rb:8:in `<top (required)>'
  /home/user/ws/repos/porta/Rakefile:1:in `require'
  /home/user/ws/repos/porta/Rakefile:1:in `<top (required)>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/rake_module.rb:29:in `load_rakefile'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:710:in `raw_load_rakefile'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:104:in `block in load_rakefile'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:103:in `load_rakefile'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/command.rb:46:in `invoke'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
  bin/rails:9:in `require'
  bin/rails:9:in `<main>'
```

My workaround is to do in Gemfile:
```ruby
gem 'audited', '~> 5.0.1', require: false
```

And in config/initializers/audited_hacks.rb:
```ruby
ActiveSupport.on_load(:active_record) do
  require 'audited'
  ...
end
```

With the workaround, one can see that ActiveRecord is triggerred by somehting else (`lib/system/database.rb` which makes more sense to me):
```
ActiveRecord init:
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `instance_eval'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:69:in `block in execute_hook'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:60:in `with_execution_control'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:65:in `execute_hook'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:49:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/base.rb:326:in `<module:ActiveRecord>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/base.rb:25:in `<top (required)>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activerecord-5.1.7/lib/active_record/connection_adapters/connection_specification.rb:195:in `spec'
  /home/user/ws/repos/porta/lib/system/database.rb:19:in `read_configuration_specification'
  /home/user/ws/repos/porta/lib/system/database.rb:11:in `configuration_specification'
  /home/user/ws/repos/porta/lib/system/database.rb:27:in `adapter_method'
  /home/user/ws/repos/porta/lib/system/database.rb:31:in `oracle?'
  /home/user/ws/repos/porta/config/initializers/oracle.rb:3:in `<top (required)>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `block in load'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:286:in `load'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:655:in `block in load_config_initializer'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/activesupport-5.1.7/lib/active_support/notifications.rb:168:in `instrument'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:654:in `load_config_initializer'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:612:in `block (2 levels) in <class:Engine>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:611:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/engine.rb:611:in `block in <class:Engine>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `instance_exec'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:30:in `run'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:59:in `block in run_initializers'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:48:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:48:in `tsort_each_child'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:415:in `call'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:347:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:347:in `call'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/initializable.rb:58:in `run_initializers'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:353:in `initialize!'
  /home/user/ws/repos/porta/config/environment.rb:6:in `<top (required)>'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:329:in `require'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:329:in `require_environment!'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/application.rb:445:in `block in run_tasks_blocks'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `block in execute'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:281:in `execute'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rake.rb:18:in `execute_with_bugsnag'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:243:in `block in invoke_prerequisites'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:241:in `invoke_prerequisites'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:218:in `block in invoke_with_call_chain'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/2.6.0/monitor.rb:235:in `mon_synchronize'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:199:in `invoke_with_call_chain'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/task.rb:188:in `invoke'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:160:in `invoke_task'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block (2 levels) in top_level'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `each'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:116:in `block in top_level'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:125:in `run_with_threads'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:110:in `top_level'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/rake-13.0.6/lib/rake/application.rb:186:in `standard_exception_handling'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/command.rb:46:in `invoke'
  /home/user/.asdf/installs/ruby/2.6.7/lib/ruby/gems/2.6.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
  bin/rails:9:in `require'
  bin/rails:9:in `<main>'
```

But I think Audited should not cause ActiveRecord initialization just because it is loaded.

**Comment by akostadinov** [comment]
hah, I see that 5.0.2 was just released with a fix... #592
