### ISSUE TITLE
Audited 5.1.0 - ArgumentError: A class was passed to `:class_name` but we are expecting a string.

### ISSUE THREAD

**Issue by TiuTalk** [collectiveidea/audited#649]
I'm getting the following error on audited v5.1.0 with rails v7.0.4.1:

```
ArgumentError: A class was passed to `:class_name` but we are expecting a string.

/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/reflection.rb:322:in `ensure_option_not_given_as_class!'
/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/reflection.rb:453:in `initialize'
/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/reflection.rb:18:in `new'
/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/reflection.rb:18:in `create'
/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/associations/builder/association.rb:50:in `create_reflection'
/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/associations/builder/association.rb:32:in `build'
/vendor/bundle/ruby/3.1.0/gems/activerecord-7.0.4.1/lib/active_record/associations.rb:1467:in `has_many'
/vendor/bundle/ruby/3.1.0/gems/audited-5.1.0/lib/audited/auditor.rb:82:in `audited'
/app/models/event.rb:3:in `<class:Event>'
```

The line 3, on the `Event` model, is where I call `audited`.

**Comment by danielmorrison** [comment]
Fixed in 5.2.0.
