### ISSUE TITLE
When running rspec I get this error: Undefined local variable or method `audited'

### ISSUE THREAD

**Issue by rafmagana** [collectiveidea/audited#98]
The `audited` method works in the app, but when I run the specs it throws that error, any idea?

**Comment by dominathan** [comment]
Late to the party but I am stuck on this problem trying to upgrade a rails application.  Any ideas?

**Comment by MSchmidt** [comment]
@dominathan are you upgrading to rails 5? Then make sure to use the gem from github. Stable branch is not rails 5 ready yet.

```ruby
gem 'audited', github: 'collectiveidea/audited'
gem "rails-observers", github: 'rails/rails-observers'
```

**Comment by dominathan** [comment]
I am slowly upgrading to ralis 5 but am stuck on rails 4.1.6 at the moment.  I am trying to run the rspec spec/ test suite but I'm failing with the audited class.  Here is the spec_helper.rb

```
require 'rubygems'
require 'simplecov'

SimpleCov.start

ENV["RAILS_ENV"] ||= 'test'
require File.expand_path("../../config/environment", __FILE__)
require 'rspec/rails'
require 'faker'
require 'faker/medical/patient'
require 'faker/medical/dea'
require 'faker/medical/npi'
require 'faker/medical/ssn'
require 'database_cleaner'
require 'rspec/autorun'

# Requires supporting files with custom matchers and macros, etc,
# in ./support/matchers and its subdirectories.
Dir["#{File.dirname(__FILE__)}/support/matchers/**/*.rb"].each {|f| require f}

# require File.join(File.dirname(__FILE__), 'support', 'capybara_support')
# require File.join(File.dirname(__FILE__), 'support', 'integration_example_group')
require File.join(File.dirname(__FILE__), 'support', 'rake_shared_context')
require File.join(File.dirname(__FILE__), 'support', 'rspec_candy')

# Or, if you're using rspec-mocks in another context:
# RSpec::Mocks.configuration.syntax = :should


RSpec.configure do |config|
  # config.include Audited
  # config.before(:each) do
  #   Audited.audit_class = Audited::Adapters::ActiveRecord::Audit
  # end

  config.infer_spec_type_from_file_location!

  #need to update all tests to use expect syntax instead of should syntax and then remove the following:
  # config.expect_with(:rspec) { |c| c.syntax = :should }
  config.mock_with :rspec do |mocks|
    mocks.syntax = :should
    mocks.yield_receiver_to_any_instance_implementation_blocks = false
  end

  config.include FactoryGirl::Syntax::Methods

  Disable auditing of models so tests will run faster
  models = Audited.audit_class.audited_classes
  models.each do |model|
    model.try(:disable_auditing)
  end

  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.start

    fake_geocode = [123.456, 123.456]
    Patient.any_instance.stub(:geocode).and_return fake_geocode

    unless @do_not_stub_cloudq_jobs
      Cloudq::Publish.any_instance.stub(:job) {true}
    end

    unless @do_not_stub_audit_callbacks
      [:create, :create!, :update, :destroy].each do |callback|
        Audited.audit_class.any_instance.stub(callback) {true}
      end
    end
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end

  config.mock_with :rspec
  config.fixture_path = "#{::Rails.root}/spec/fixtures"
  config.use_transactional_fixtures = false

  # # Suppress st messages
  # # These need to comment this out if you are using a debugger (i.e., byebug)
  # original_stderr = $stderr
  # original_stdout = $stdout
  # config.before(:all) do
  #   # Redirect stderr and stdout
  #   $stderr = File.open(File::NULL, "w")
  #   $stdout = File.open(File::NULL, "w")
  # end
  # config.after(:all) do
  #   $stderr = original_stderr
  #   $stdout = original_stdout
  # end
end
```

And here is the error

```
No DRb server is running. Running in local process instead ...
Coverage report generated for RSpec to /Users/.../. 2301 / 6182 LOC (37.22%) covered.
/Users/nhall/.rvm/gems/ruby-2.3.0/gems/activerecord-4.1.15/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method `audited' for #<Class:0x007fe512890130> (NoMethodError)
       	from /Users/.../app/models/external_system.rb:5:in `<class:ExternalSystem>'
```

Been stuck on this for awhile now.  Any help would be greatly appreciated.

**Comment by dominathan** [comment]
The issue has now changed so that it has trouble loading ActiveModel::Observing

```
There was an error while trying to load the gem 'audited-activerecord'. (Bundler::GemRequireError)
Gem Load Error is: uninitialized constant ActiveModel::Observing
```
Do I need to require ActiveModel::Observing somewhere in my test suite? I can use it fine in `rails console`

**Comment by dominathan** [comment]
Any ideas going on with this? Works fine in development but can't get it in testing.

**Comment by danielmorrison** [comment]
@dominathan I don't have an obvious answer, and I use RSpec with audited frequently. It sounds like it isn't getting required properly. Do you have it in a strange group in the `Gemfile`? Doing something non-standard with how gems are required in `application.rb`? Are you doing anything special with tests to make them run faster? Is another gem causing issues (you could try moving the `audited` gem higher or lower in the list)? 

There's probably a common issue here, but I haven't seen it. 

You could try adding `require "audited"` at the bottom of your list of requires in `spec_helper`. If that works, then something else is causing it to not load or get unloaded.

**Comment by dominathan** [comment]
Not sure if will help anyone, but I have to make an initializer that require 'audit' if the Rails.env == 'test'

**Comment by MrHubble** [comment]
I believe stable branch is now Rails 5 ready (https://github.com/collectiveidea/audited/commit/4d4799cf7f9740d2a984839f8b8bc3c893531dea). This issue can possibly be closed.

**Comment by laserlemon** [comment]
@MrHubble Thank you!
